-- 코드를 작성해주세요
WITH RECURSIVE GENERATION_CTE AS (
    -- 1. 1세대 찾기 (초기 서브쿼리)
    SELECT ID, PARENT_ID, 1 AS GENERATION
    FROM ECOLI_DATA
    WHERE PARENT_ID IS NULL
    
    UNION ALL
    
    -- 2. 2세대부터 N세대까지 반복해서 세대 부여 (재귀 서브쿼리)
    SELECT E.ID, E.PARENT_ID, G.GENERATION + 1 AS GENERATION
    FROM ECOLI_DATA E
    JOIN GENERATION_CTE G ON E.PARENT_ID = G.ID
)

-- 3. 자식이 없는 개체들만 골라 세대별로 집계
SELECT 
    COUNT(*) AS COUNT, 
    GENERATION
FROM GENERATION_CTE
WHERE ID NOT IN (
    -- 누군가의 부모(PARENT_ID)인 ID들을 제외시킨다. = 자식이 없는 개체
    SELECT DISTINCT PARENT_ID 
    FROM ECOLI_DATA
    WHERE PARENT_ID IS NOT NULL   
)
GROUP BY GENERATION
ORDER BY GENERATION;