-- 코드를 입력하세요
SELECT b.CATEGORY, SUM(s.SALES) AS TOTAL_SALES
FROM BOOK b
JOIN BOOK_SALES s
    ON b.BOOK_ID = s.BOOK_ID
WHERE S.SALES_DATE >= '2022-01-01' 
  AND S.SALES_DATE < '2022-02-01'
GROUP BY b.CATEGORY
ORDER BY b.CATEGORY ASC
;